"""Add synthesis dependency tracking fields

Revision ID: 23c28d5dbd93
Revises: f46ce71918ec
Create Date: 2025-06-16 20:33:45.053963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c28d5dbd93'
down_revision = 'f46ce71918ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_stale', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_item_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('needs_regeneration', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('dependency_item_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.drop_column('dependency_item_ids')
        batch_op.drop_column('needs_regeneration')
        batch_op.drop_column('last_item_update')
        batch_op.drop_column('is_stale')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
