"""Add current_task_id to AgentState and create CeleryTaskState table

Revision ID: 7b5e58e92364
Revises: 3464cd7e14d7
Create Date: 2025-07-09 16:44:30.059045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5e58e92364'
down_revision = '3464cd7e14d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('task_queue_size', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_agent_state_current_task_id', 'celery_task_state', ['current_task_id'], ['task_id'])

    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.alter_column('synthesis_short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.alter_column('synthesis_short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('agent_state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_state_current_task_id', type_='foreignkey')
        batch_op.drop_column('task_queue_size')
        batch_op.drop_column('current_task_id')

    # ### end Alembic commands ###
