"""Add TweetBookmark table

Revision ID: tweet_bookmark_001
Revises: a1b2c3d4e5f6
Create Date: 2025-07-28 09:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'tweet_bookmark_001'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=50), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('full_url', sa.String(length=500), nullable=False),
    sa.Column('first_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_bookmarked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_bookmarks_tweet_id'), 'tweet_bookmarks', ['tweet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_bookmarks_tweet_id'), table_name='tweet_bookmarks')
    op.drop_table('tweet_bookmarks')
    # ### end Alembic commands ###