"""Add human_readable_name and run_report to CeleryTaskState

Revision ID: d1ec40203de8
Revises: 7b5e58e92364
Create Date: 2025-07-18 09:24:44.241451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ec40203de8'
down_revision = '7b5e58e92364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_readable_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('run_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_task_state', schema=None) as batch_op:
        batch_op.drop_column('run_report')
        batch_op.drop_column('human_readable_name')

    # ### end Alembic commands ###
