"""add synthesis short name to synthesis model

Revision ID: f46ce71918ec
Revises: 23c28d5dbd93
Create Date: 2024-12-26 10:32:35.729701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ce71918ec'
down_revision = '23c28d5dbd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synthesis_short_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.drop_column('synthesis_short_name')

    # ### end Alembic commands ###
