"""Add synthesis_short_name to SubcategorySynthesis

Revision ID: f46ce71918ec
Revises: 
Create Date: 2025-06-13 09:59:44.857120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46ce71918ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synthesis_short_name', sa.String(length=50), nullable=True))
        batch_op.alter_column('sub_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint('uq_main_sub_category', ['main_category', 'sub_category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory_synthesis', schema=None) as batch_op:
        batch_op.drop_constraint('uq_main_sub_category', type_='unique')
        batch_op.alter_column('sub_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('synthesis_short_name')

    # ### end Alembic commands ###
